### ISSUE TITLE
Setting a variable to a path without quotes causes autocd

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#576]
`let d = ~/pictures` will autocd me into the `~/pictures` directory.

**Comment by jntrnr** [comment]
this example is also trying to run `~/pictures` as a command and send its result to `$d`

We could change this by requiring that you wrap the right-hand side in `()` to call commands

**Comment by kubouch** [comment]
I was always wrapping into `()` by default, I didn't know we omit the `()` :-D.

I think removing the `()` requirement might get a seemingly unexpected results:
```
> let x = echo " foo "

> $x
 foo 

> let x = echo " foo " | str trim

> $x   # No whitespace removed! How come!?
 foo 
```
I feel like this bug is bound to happen so I would prefer to be on the safe side and require the parentheses.

**Comment by jntrnr** [comment]
yeah, I can add back in the requirement that it's wrapped in parens

**Comment by kubouch** [comment]
Would math operations need to be wrapped in parens? I think these can stay without the requirement, right?

**Comment by jntrnr** [comment]
Yeah, I went back and thought about it a bit. I want to leave the expression parsing for the right-hand side, so you can do calls and whatnot without a paren *but* I also want to see what it's like if we require that a `let` command is a statement rather than part of a pipeline.

Here's kinda what I'm thinking:
https://github.com/nushell/engine-q/pull/594

I also went ahead in that PR and move auto-cd so that it only happens in the CLI and only when on a line by itself.

**Comment by kubouch** [comment]
I think that solves it. It no longer does autocd and gives a clear error if you use a pipeline :+1:
