### ISSUE TITLE
Modules draft proposal

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#64]
(Related to #56)

note: this is just some scribbles of a possible design direction. definitely open for comment

# Modules

Modules give languages a way to better share and reuse common functionality an a program or library. We'd like to implement a type of modules in Nushell that is both flexible and easy to use. Specifically, we'd like to cover the following use cases:

* The ability to create a module of code that can be imported and used
* The ability to use a module as an "overlay" that can later be removed, allowing us to module the effect of virtual environments as a declarative part of the Nushell language
* Replace the `shells` concept of early Nushell with a much more structured and easy to extend form in the Nushell language. Likewise replace the `autoenv` concept.

It's possible that all the above may fit into a module concept.

## Possible module design

Modules in TypeScript and Rust follow a similar form: there are inner modules (or internal modules) and file-based (or external modules). Both use a manual way of exporting symbols from the module to the scope that is consuming the module.

I propose we follow a similar path for Nushell.

Example of a file-based module:
```
# math.nu

export def add [x, y] { $x + $y }
```
```
# main.nu

use math.add

add 1 2
```

Example of inner module:
```
# all_in_one.nu

module math {
  export def add [x, y] { $x + $y }
}

use math.add
add 1 2

# -or-

math.add 1 2
```

### Modules

Blocks that export definitions can be used as a "block of definitions". These expose definitions outside of the block, making them available for import.

Blocks can export the following types of things:

* definitions (custom commands)
* environment variables
* aliases
* modules

Let's look at each of these.

### Definitions in modules

A definition in a module is a custom command exported by the module. These custom commands can do their own importing to perform the task, as well as call other custom commands in the same module.

A definition has to be `export`ed from the module to be visible outside of the module. Modules can have definitions that aren't exported, but instead called by other definitions to do the necessary work. These helpers, because they aren't exported, would not be publicly visible outside of the module.

My assumption here is that since we never evaluate the module, definitions can't "close" over variables inside of the module and have to only use the variables created by the parameters given to the custom command (and perhaps the exported environment variables).

### Environment variables in modules

Since we want to be able to use modules as overlays, virtual envs, etc, it's helpful to be able to set environment variables and expose them as exports. How these are assigned may need a bit of work. My first guess is that a module's environment is a little different than an environment variable.

(not real syntax)

```
module math {
  export env.MAX_INT = { 65535 }
}
```

In the example, I show environments from the module being exported as a block instead of as a simple value. This is because we may want to run commands (like `pwd`) to create the environment variable when we create the overlay. Unless we have a way to run a modules and set these values.

Alternate design: the `use` command could run a module *once*. This would be used to set the variables to their correct values and after this point, as long as you're in a scope where the `use` was visible, you could access the variables without re-running the module.

### Aliases

Aliases would work as aliases today, describing a transformation to take place during parsing. Modules and module imports would all need to be visible to the parser for this to occur correctly.

### Modules

Modules that export other modules give us a way of creating larger modules. Once in scope, you could use `.` to access module exports.

**Comment by fdncred** [comment]
Just thinking through some things here/brainstorming.

1. Since prompt_command is an env var, we should be able to set that with a module. it would be cool to change your prompt when you 'enter' a module.
2. Will there be a 'startup' section of the module, so that something is ran once you 'enter' a module. if we're using this as a drop in replacement for autoenv, we may need to run something on cd-ing to a folder. if we're using modules as a way to import math.nu that has all my math commands, then we don't want to run things... i don't think.
3. I'm assuming modules will support all the normal language features perhaps like nushell literal tables, nushell lists. i.e. it's not going to be a subset of the nu language but fully support all nushell syntax.
4. maybe nushell always runs in a module/overlay i.e. on launch, one of the first things it does is load an overlay as the 'root' overlay, so there's always at least 1 on the stack. this comment comes from thinking that perhaps we could/should remove the config.toml and use the 'root.module' as the initial configuration, that uses nushell to define env-vars/variables/defs/aliases instead of toml?
5.  building on number 4, perhaps we have a color_config.mod, text_view.mod, env.mod, line_editor.mod, path.mod, plugin_dirs.mod, startup.mod, path.mod, root.mod that all get 'sourced/imported' during launch? note the name in <name>.mod are sections the config.toml that i'm looking at.

**Comment by kubouch** [comment]
@fdncred 
1. I think this is a planned feature.
2. This might be quite tricky. Would it hurt too much not to be able to run arbitrary code when entering a directory? Alternatively, we could have the 'enter dir' hook as follows: 1. run code, 2. import module
3. Everything will be supported, but at the root level you'll be restricted to only the exportable statements (def, alias, etc.) and literals for variables (i.e., the value of vars / env vars needs to be known at parse time).
4. & 5. Yeah. that's how I see it, too. Other shells (at least bash and fish) use a shell script for config so we could do the same.

**Comment by jntrnr** [comment]
Initial implementations for this are now available in https://github.com/nushell/engine-q

**Comment by kubouch** [comment]
I'll close this as we're done with the initial implementation and further progress will need more design iterations.
