### ISSUE TITLE
question/ Add a comment somewhere about `cargo test`

### ISSUE THREAD

**Issue by zhiburt** [nushell/engine-q#821]
Hi there

I just noted that `cargo test` fails unless `cargo build` has been run before.

```log
test result: FAILED. 0 passed; 217 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s
```

It's not that obvious I would say.
May it deserve to be noted somewhere, like `CONTRIBUTING.md`?

Not sure if it is a duplicate.

Thank you.
Take care.

**Comment by fdncred** [comment]
I do most of this. I don't have to do number 1 because vscode does it for me.

1. `cargo fmt --all` (formats all your changes)
2. `cargo build --features=extra` (this builds all + plugins)
2. `cargo run --features=extra` (this will run it)
3. `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` (run linting)
4. `cargo test --all --all-features` (run tests)

**Comment by zhiburt** [comment]
Yep but don't you think it's worthwhile to highlight somewhere that "to be able to run tests you need firstly build a crate"?

**Comment by fdncred** [comment]
ya, all those points should be in our documentation somewhere. however, I assumed that it's just the way rust works. maybe it's only our solution. I'm not sure.

**Comment by zhiburt** [comment]
It's not a default for sure.
Shall I close it or it being open?

**Comment by zhiburt** [comment]
I guess its here https://github.com/nushell/engine-q/blob/af52def93cc8d36bb48ea02cdad09ae783325132/src/tests.rs#L25-L47

**Comment by jntrnr** [comment]
Yeah, that's it. `Command::cargo_bin("engine-q")?; ` needs the binary to already be built

**Comment by fdncred** [comment]
@zhiburt the pull request template has been updated to include some of the steps above. closing this in favor of that. please re-open if you don't agree.
